badass-courses/course-builder

- apps/course-builder-web/.env.example
- apps/course-builder-web/package.json
- apps/course-builder-web/src/app/api/postmark/webhook/route.ts
- apps/course-builder-web/src/app/test/page.tsx
- apps/course-builder-web/src/app/tutorials/[module]/edit/_form.tsx
- apps/course-builder-web/src/components/lesson-list/list.tsx
- apps/course-builder-web/src/emails/basic-email.tsx
- apps/course-builder-web/src/env.mjs
- apps/course-builder-web/src/inngest/events/postmark-webhook.ts
- apps/course-builder-web/src/inngest/functions/notify/creator/user-signup.ts
- apps/course-builder-web/src/inngest/functions/notify/creator/weekly-signups.ts
- apps/course-builder-web/src/inngest/functions/postmark/postmarks-webhooks-handler.ts
- apps/course-builder-web/src/inngest/functions/user-created.ts
- apps/course-builder-web/src/inngest/inngest.config.ts
- apps/course-builder-web/src/inngest/inngest.server.ts
- apps/course-builder-web/src/server/auth.ts
- apps/course-builder-web/src/server/db/schema.ts
- apps/course-builder-web/src/utils/send-an-email.ts
- pnpm-lock.yaml
postmark requires that any non-transactional (broadcast/bulk) emails have an unsubscribe link that **they** manage
this adds that to the Basic email template as well as connecting Postmark webhooks internally to Inngest events
also sketched in the idea of communication preferences that might get removed later
> feat: process unsubs from postmark

- apps/course-builder-web/src/app/tips/[slug]/page.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/app/tips/_components/new-tip-form.tsx
- apps/course-builder-web/src/inngest/functions/tips/chat.ts
- apps/course-builder-web/src/lib/tips.ts
- apps/course-builder-web/src/trpc/api/routers/tips.ts
It's possible that the `getTip` function is directed to look up a Tip
that doesn't exist in Sanity. So the type needs to reflect that by
having a return type of `Tip | null`. The type errors then helpfully
pointed to some places where we needed to handle the `null` case.
> feat: handle scenario where getTip is null

- apps/course-builder-web/package.json
- apps/course-builder-web/sanity/schemas/documents/article.ts
- apps/course-builder-web/src/app/[article]/opengraph-image.tsx
- apps/course-builder-web/src/app/[article]/page.tsx
- apps/course-builder-web/src/app/articles/_components/edit-article-form.tsx
- apps/course-builder-web/src/lib/articles.ts
- packages/ui/primitives/form.tsx
- pnpm-lock.yaml
https://github.com/badass-courses/course-builder/assets/25487857/44f30638-e259-4b4e-9647-debed6a3086e
- used next's open graph image file convention with `ImageResponse` to generate default social image for articles. allows for more granular control over cloudinary approach.
- added `socialImage: string` field to article resource
- in editor, we have an interactive preview coupled with input field for a custom image url and also "reset to default" button that allows switching back to default/generated version. you can also drag and drop an image from media browser.
> feat(articles): open graph image template + editor with preview

- apps/course-builder-web/src/app/_components/landing.tsx
- apps/course-builder-web/src/app/articles/_components/edit-article-form.tsx
- apps/course-builder-web/src/app/page.tsx
made some simple changes stacking meta fields and content on mobile. lmk if you prefer different sorting.
> style(articles): mobile edit form

- apps/course-builder-web/package.json
- apps/course-builder-web/src/app/_components/codemirror.tsx
- apps/course-builder-web/src/app/_components/resource-assistant.tsx
- apps/course-builder-web/src/app/_components/resource-chat-response.tsx
- apps/course-builder-web/src/app/articles/[slug]/edit/page.tsx
- apps/course-builder-web/src/app/articles/_components/cloudinary-media-browser.tsx
- apps/course-builder-web/src/app/articles/_components/edit-article-form.tsx
- apps/course-builder-web/src/app/layout.tsx
- apps/course-builder-web/src/app/page.tsx
- apps/course-builder-web/src/app/tips/[slug]/edit/page.tsx
- apps/course-builder-web/src/app/tips/_components/cloudinary-media-browser.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/components/navigation.tsx
- apps/course-builder-web/src/components/navigation/links.tsx
- apps/course-builder-web/src/components/navigation/theme-toggle.tsx
- apps/course-builder-web/src/components/theme-provider.tsx
- apps/course-builder-web/src/styles/globals.css
- packages/ui/index.tsx
- packages/ui/package.json
- packages/ui/primitives/resizable.tsx
- pnpm-lock.yaml
- implemented [Resizable](https://ui.shadcn.com/docs/components/resizable) panes
- to consider: store size values 
- consolidated edit routes layout and added [ScrollAreas](https://ui.shadcn.com/docs/components/scroll-area)
- minor refactor of tip and article edit forms, changed `form` wrapper so that multiple form elements can coexist
- added theme provider and toggle
https://github.com/badass-courses/course-builder/assets/25487857/4709f17b-b4ae-4ddf-9a5a-b4c264db8a6b
> style: resizable panes and dark mode

- apps/course-builder-web/src/server/db/schema.ts
one thing i think we might want to avoid is the detachment from "author/instructor" and the user and think about this model from the perspective of a single database where we have a user and a user profile
in sanity this would mean that an "author" is a pointer
another thing i've been considering is the idea of ownership versus authorship and how that affects the model. a resource is "owned by" a user or set of users, but the owners arent necessarily the authors
you've got a set of permissions for any given resource like read/write/managepublished collections (lessons, articles, etc) have sets of contributors (credits), which is different in practice than ownership. a contributor doesn't necessarily have ability to edit/manage the resource for instance.
so there is the ability to …
> feat: content metadata to represent content pieces

- .changeset/wild-glasses-design.md
- apps/course-builder-web/src/app/layout.tsx
- apps/course-builder-web/src/lib/props-for-commerce.ts
- apps/course-builder-web/src/pricing/coupon-context.tsx
- apps/course-builder-web/src/pricing/redeem-dialog.tsx
- apps/course-builder-web/src/pricing/use-coupon.tsx
- apps/course-builder-web/src/styles/globals.css
- apps/course-builder-web/src/styles/redeem-dialog.css
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/core/src/lib/actions/redeem.ts
- packages/core/src/lib/send-verification-request.ts
- packages/core/src/lib/utils/web.ts
> feat: redeem 100% off coupons

- apps/value-based-design/src/app/(commerce)/products/[slug]/page.tsx
- apps/value-based-design/src/app/(content)/events/[slug]/page.tsx
- apps/value-based-design/src/app/(content)/workshops/[module]/page.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/pricing-widget.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/workshop-page-props.ts
- apps/value-based-design/src/app/(content)/workshops/_components/workshop-pricing-server.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/workshop-pricing.tsx
- apps/value-based-design/src/lib/module.ts
- apps/value-based-design/src/lib/pricing-query.ts
- apps/value-based-design/src/lib/workshops-query.ts
This adds the `PricingWidget` Vojta created for pro-nextjs to value based design. 
I went ahead and broke out all the pricing widget logic from the module page and added a `pricing-widget-server` component that handles that loading/logic so the module page imports the `PricingWidget` from `pricing-widget-server`. Felt cleaner to encapsulate that logic in a component rather than clogging up the module page
> feat(vbd): add pricing widget to workshop module page

- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/core/src/inngest/commerce/event-purchase-status-updated.ts
- packages/core/src/inngest/index.ts
- packages/core/src/lib/pricing/process-stripe-webhook.ts
This adds a `PURCHASE_STATUS_UPDATED_EVENT` that we can send to inngest with a charge Id (identifier which is different than the `merchantChargeId` we store on a purchase) and status. For the current use-case, this sends `Refunded` and `Disputed` status's when we receive `charge.refunded`  or `charge.dispute.created` webhook events from stripe.
The result is a purchase with it's status updated:
> feat(cb): handle stripe refund and dispute webhook events

- apps/value-based-design/src/ability/index.ts
- apps/value-based-design/src/ability/purchase-validators.test.ts
- apps/value-based-design/src/ability/purchase-validators.ts
- apps/value-based-design/src/app/(content)/workshops/_components/tutorial-lesson-list.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/workshop-pricing-server.tsx
- apps/value-based-design/src/lib/modules-query.ts
- apps/value-based-design/src/trpc/api/routers/ability.ts
- apps/value-based-design/src/utils/get-current-ability-rules.ts
This mimics the [work](https://github.com/badass-courses/course-builder/pull/215) @vojtaholik did in pro-nextjs.
Primarily implements `getCurrentAbilityRules` that return whether a user can view content they've purchased. Also updates the lesson list with lock icons for lessons that users don't have access too
> feat(vbd): add ability rules and update tutorial lesson list

- .changeset/green-radios-sniff.md
- apps/pro-aws/src/app/(content)/_components/video-player-overlay.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/(view)/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/_components/lesson-progress-toggle.tsx
- apps/pro-aws/src/app/(content)/tutorials/_components/tutorial-lesson-list.tsx
- apps/pro-aws/src/lib/progress.ts
- apps/pro-nextjs/src/app/(content)/tutorials/_components/tutorial-lesson-list.tsx
- apps/pro-nextjs/src/lib/progress.ts
- apps/pro-nextjs/src/trpc/api/routers/progress.ts
- apps/value-based-design/src/app/(content)/_components/video-player-overlay.tsx
- apps/value-based-design/src/app/(content)/tutorials/_components/lesson-progress-toggle.tsx
- apps/value-based-design/src/app/(content)/tutorials/_components/tutorial-lesson-list.tsx
- apps/value-based-design/src/app/(content)/workshops/[module]/[lesson]/(view)/page.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/tutorial-lesson-list.tsx
- apps/value-based-design/src/lib/progress.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/core/src/adapters.ts
- packages/core/src/schemas/resource-progress-schema.ts
> feat(pnjs): load progress with less queries

- apps/js-visualized/src/app/page.tsx
- apps/js-visualized/src/components/landing/introduce-author.tsx
- apps/js-visualized/src/components/landing/question-and-answer.tsx
- apps/js-visualized/src/components/navigation.tsx
- apps/js-visualized/src/styles/globals.css
- apps/js-visualized/tailwind.config.ts
I noticed that when Light Appearance is enabled on iPhone, some colors are distorted:
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> fix(jsv): fix colors and clean up

- apps/egghead/src/lib/posts-query.ts
Uses the same guid for a posts `id`, `slug`, and slug in rails lesson object
> feat(egh): enforce consistent guid on post creation

- apps/egghead/src/app/(content)/[post]/page.tsx
- apps/egghead/src/app/(content)/[post]/transcript.tsx
- apps/egghead/src/app/(content)/posts/_components/edit-post-form-metadata.tsx
- apps/egghead/src/app/(content)/posts/_components/edit-post-form.tsx
- apps/egghead/src/app/(content)/posts/_components/post-player.tsx
- apps/egghead/src/lib/posts-query.ts
- apps/egghead/src/lib/posts.ts
- packages/ui/resources-crud/new-resource-with-video-form.tsx
This allows instructors to create posts without a `videoResource` attached to the post. On the edit screen instructors can add a video if they end up wanting one on the post.
I also added other metadata to post edit form like visibility, state, SEO description, and github. We don't use them on the egghead side yet but having that data won't hurt.
> feat(egh): allow creating non-video posts

- apps/ai-hero/src/components/share.tsx
- apps/ai-hero/src/config.ts
Adds a bluesky share button for ai-hero
> feat(ai): add bluesky to share component

- apps/egghead/src/app/admin/_components/instructor-data-table.tsx
- apps/egghead/src/app/admin/instructors/invite/_components/invite-instructor-form.tsx
- apps/egghead/src/app/admin/instructors/invite/_components/invites-data-table.tsx
- apps/egghead/src/app/admin/instructors/invite/actions.ts
- apps/egghead/src/app/admin/instructors/invite/page.tsx
- apps/egghead/src/app/admin/layout.tsx
- apps/egghead/src/db/schema.ts
- apps/egghead/src/db/schemas/invites.ts
- apps/egghead/src/inngest/events/instructor-invite-created.ts
- apps/egghead/src/inngest/functions/instructor-invite-created.ts
- apps/egghead/src/inngest/inngest.config.ts
- apps/egghead/src/inngest/inngest.server.ts
This enables working on the instructor invites project [EGG-389](https://linear.app/skillrecordings/issue/EGG-389/invite-instructors-through-course-builder) by setting up an invites table that will track the state of an invite as it's sent out and accepted by instructor. The invites table is set up to be local to egghead course builder only under `db/schemas`
This also sets up UI to send those invites out for admin:
> feat(egh): set up instructor invites table and dashboard

- apps/egghead/src/inngest/functions/sanity/create-course-in-sanity.ts
- apps/egghead/src/inngest/functions/sanity/sync-lesson-to-sanity.ts
- apps/egghead/src/inngest/inngest.config.ts
- apps/egghead/src/lib/posts-query.ts
- apps/egghead/src/lib/sanity-content-query.ts
- apps/egghead/src/lib/sanity-content.ts
This PR introduces a function for creating course documents in Sanity when a post with the "course" type is created. 
I've also brought in some new schemas and made types more consistent. 
- Added `createCourseInSanity.ts` function to handle course creation in Sanity
- Integrated with POST_CREATED_EVENT to automatically create courses
- Added course creation function to inngest config
- Consolidated and standardized Sanity schema types
- Introduced new base schemas (SystemFields, Reference, Image, Slug)
- Renamed schema constants to follow consistent PascalCase convention
- Added SanityCourse schema type and validation
- Updated references to schema types
- Improved type safety with more specific schema definitions
- Renamed ambiguous type names for better clarity
> feat(egh): Refactor Sanity Schema Types and Add Course Creation Function

- apps/egghead/src/lib/egghead.ts
- apps/egghead/src/lib/posts-query.ts
- apps/egghead/src/lib/typesense-query.ts
- apps/egghead/src/lib/typesense.ts
- Added schema validation for Typesense documents using Zod
- Split Typesense logic into separate query and schema files
- Added `published_at` field support in egghead lesson updates
- Enhanced instructor metadata in Typesense documents
- Added tags to Typesense documents
These changes improve the reliability and maintainability of our Typesense integration:
1. Schema validation ensures we're sending valid data to Typesense
2. Better organization of code with separate schema and query files
3. Proper tracking of publish dates for content
4. Trimmed TypeSense records down to what was needed
[EGG-392: Lessons previously published via course builder have null published_at attributes](https://linear.app/skillrecordings/issue/EGG-392/lessons-previously-published-via-course-builder-have-null-pu …
> fix: Improve Lesson Upsert to Typesense

- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/edit-list-form-metadata.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/edit-list-form.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/hit.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/lesson-list/data/tree.ts
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/lesson-list/pieces/tree/constants.ts
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/lesson-list/pieces/tree/tree-context.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/lesson-list/pieces/tree/tree-item.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/lesson-list/tree.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/list-resources-edit.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/resources-infinite-hits.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/_components/selection-context.tsx
- apps/ai-hero/src/app/(content)/lists/[slug]/edit/page.tsx
- apps/ai-hero/src/app/(content)/lists/_components/create-list-form.tsx
- apps/ai-hero/src/app/(content)/lists/_components/lists-table.tsx
- apps/ai-hero/src/app/(content)/lists/page.tsx
- apps/ai-hero/src/app/(content)/posts/[slug]/edit/page.tsx
- apps/ai-hero/src/app/(content)/posts/_components/add-to-list.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form-metadata.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form-mobile.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/searchbox.tsx
- apps/ai-hero/src/app/admin/pages/_components/edit-pages-form.tsx
- apps/ai-hero/src/lib/lists-query.ts
- apps/ai-hero/src/lib/lists.ts
- apps/ai-hero/src/lib/posts-query.ts
- apps/go-local-first/src/app/admin/pages/_components/edit-pages-form.tsx
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
- packages/ui/resources-crud/panels/edit-resources-body-panel.tsx
> feat(aih): edit and create lists

- apps/ai-hero/src/app/(content)/[post]/page.tsx
- apps/ai-hero/src/app/(content)/_components/post-next-up-from-list-pagination.tsx
- apps/ai-hero/src/app/(content)/lists/_components/create-list-form.tsx
- apps/ai-hero/src/app/(content)/lists/_components/lists-table.tsx
- apps/ai-hero/src/app/(content)/lists/page.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form-metadata.tsx
- apps/ai-hero/src/app/(content)/posts/_components/post-player.tsx
- apps/ai-hero/src/app/(content)/posts/_components/post-video-subscribe-form.tsx
- apps/ai-hero/src/components/codehike/scrollycoding.tsx
- apps/ai-hero/src/lib/lists-query.ts
- apps/ai-hero/src/utils/get-nextup-resource-from-list.ts
> feat(aih): implement next up from list retrieval for posts & ui

- apps/ai-hero/src/app/(content)/_components/authed-video-player.tsx
- apps/ai-hero/src/app/(content)/_components/lesson-player.tsx
- apps/ai-hero/src/app/(content)/posts/_components/post-player.tsx
- apps/ai-hero/src/markdown/mdx-components.tsx
- apps/astro-party/src/app/(content)/_components/authed-video-player.tsx
- apps/astro-party/src/app/(content)/_components/post-player.tsx
- apps/astro-party/src/app/(content)/workshops/[module]/[lesson]/edit/_components/lesson-player.tsx
- apps/astro-party/src/components/resources-crud/lesson-player.tsx
- apps/course-builder-web/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/lesson-player.tsx
- apps/egghead/src/app/(content)/posts/_components/post-player.tsx
- apps/epic-react/src/app/(content)/posts/_components/post-player.tsx
- apps/go-local-first/src/app/(content)/posts/_components/post-player.tsx
- packages/commerce-next/src/post-purchase/welcome-page.tsx
this adds post metadata for all the mux player instances in course builder products.
> feat: add post metadata to mux player

- apps/egghead/src/app/api/posts/route.ts
- apps/egghead/src/inngest/functions/notify-slack-for-post.ts
- apps/egghead/src/lib/egghead.ts
- apps/egghead/src/lib/instructor-query.ts
- apps/egghead/src/lib/posts-new-query.ts
- apps/egghead/src/lib/posts-query.ts
Looking at the rails object after creating a course in builder I noticed 'user created' label. We were passing the instructor id as the `owner_id` which rails expects the users id so creating courses was assigning the course to wrong users.
The initial confusion might stem from the fact that `getEggheadUserProfile` gets the current users _instructor_ profile
> fix(egh): create rails playlist with egh user id not instructor id

- apps/egghead/src/lib/egghead.ts
- apps/egghead/src/lib/posts-query.ts
- apps/egghead/src/lib/typesense-query.ts
- apps/egghead/src/lib/typesense.ts
The Feed on egghead-next gets clogged up with course lessons if an instructor publishes them all at once. This adds `resources` array and `belongs_to_resource` boolean to typesense data so that we can sort (effectively filter out) lessons in courses in a new preset called `the_feed`. 
TypeSense does not let you filter on null values but the workaround is to sort missing values to the bottom (`belongs_to_resource(missing_values: first):desc`). We set `belongs_to_resource` to the id of the resource the current resource belongs to.
We also weren't updating the egghead playlist on publish to properly index it so this adds that as well
related
https://github.com/skillrecordings/egghead-next/pull/1508
> feat(egh): add course info to TypeSense
