- apps/course-builder-web/src/app/tips/[slug]/edit/page.tsx
- apps/course-builder-web/src/app/tips/_components/create-tip.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/app/tips/_components/new-tip-form.tsx
- apps/course-builder-web/src/app/tips/page.tsx
- apps/course-builder-web/src/lib/tips.ts
- apps/course-builder-web/src/trpc/api/routers/tips.ts
- apps/course-builder-web/src/trpc/react.tsx
still thinking about how the generative aspects will come into play.
if you hit "generate title" it does that process async, but it's slow so the feedback loop leaves a lot to be desired
it probably makes the most sense to give the user some way to select or approve the results when they come in
using faster models or less involved chains is another consideration for tighter feedback loops
> feat: adds an edit tip form

- apps/course-builder-web/src/app/tutorials/[module]/[lesson]/edit/page.tsx
- apps/course-builder-web/src/app/tutorials/[module]/[lesson]/page.tsx
- apps/course-builder-web/src/app/tutorials/[module]/edit/page.tsx
- apps/course-builder-web/src/app/tutorials/[module]/page.tsx
- apps/course-builder-web/src/app/tutorials/new/page.tsx
- apps/course-builder-web/src/app/tutorials/page.tsx
- apps/course-builder-web/src/components/navigation/links.tsx
- apps/course-builder-web/src/inngest/functions/user-created.ts
- apps/course-builder-web/src/lib/ability.ts
- apps/course-builder-web/src/server/sanity.server.ts
this adds /tutorials/new /tutorials/SLUG/edit
functionality to follow!
> feat: tutorial crud routes

- apps/course-builder-web/src/app/tutorials/[module]/edit/_form.tsx
- apps/course-builder-web/src/app/tutorials/[module]/edit/page.tsx
- apps/course-builder-web/src/trpc/api/routers/module.ts
https://www.loom.com/share/fc67ff00df9b4e1cbed67a57dcc59de0?sid=ab55b4e4-9a43-40a8-aaa8-848e933b6cad
> feat: sort in list updates sanity

- apps/course-builder-web/src/app/_components/chat-response.tsx
- apps/course-builder-web/src/app/layout.tsx
- apps/course-builder-web/src/app/tips/[slug]/edit/page.tsx
- apps/course-builder-web/src/app/tips/_components/create-tip.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/app/tips/_components/tip-assistant.tsx
- apps/course-builder-web/src/app/tips/_components/tip-player.tsx
- apps/course-builder-web/src/app/tips/page.tsx
- apps/course-builder-web/src/trpc/api/routers/tips.ts
- apps/course-builder-web/tailwind.config.ts
- packages/ui/primitives/scroll-area.tsx
- pnpm-lock.yaml
> style: tip edit layout

- apps/course-builder-web/README.md
This is a combination of @creeland's notes (https://roamresearch.com/#/app/egghead/page/CbOsQm5O6) and my own experience setting up the app locally.
> docs: document local setup in app README

- apps/course-builder-web/src/app/tips/_components/cloudinary-media-browser.tsx
- apps/course-builder-web/src/app/tips/_components/cloudinary-upload-widget.tsx
https://github.com/badass-courses/course-builder/assets/25487857/6b00a751-95b2-4ea7-a784-1e6a2b3cf054
> feat(mediabrowser): drag and drop images into markdown

- apps/course-builder-web/src/server/auth.ts
It was instead being assigned the `user` object that was one of the
arguments to the `session` callback function. I'm unsure why this wasn't
resulting in a type error.
> fix: fallback user.role should be 'user' string

- apps/course-builder-web/package.json
- apps/course-builder-web/src/app/api/uploadthing/core.ts
- apps/course-builder-web/src/app/articles/_components/article-assistant.tsx
- apps/course-builder-web/src/app/articles/_components/cloudinary-upload-widget.tsx
- apps/course-builder-web/src/app/articles/_components/codemirror.tsx
- apps/course-builder-web/src/app/articles/_components/edit-article-form.tsx
- apps/course-builder-web/src/app/tips/_components/cloudinary-upload-widget.tsx
- apps/course-builder-web/src/app/tips/_components/codemirror.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/app/tutorials/[module]/edit/_form.tsx
- apps/course-builder-web/src/components/lesson-list/data/tree.ts
- apps/course-builder-web/src/components/lesson-list/pieces/tree/move-dialog.tsx
- apps/course-builder-web/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/course-builder-web/src/components/lesson-list/tree.tsx
- apps/course-builder-web/src/inngest/events.ts
- apps/course-builder-web/src/inngest/functions/ai/feedback-markers.ts
- apps/course-builder-web/src/inngest/functions/articles/chat.ts
- apps/course-builder-web/src/inngest/inngest.config.ts
- apps/course-builder-web/src/inngest/inngest.server.ts
- apps/course-builder-web/src/lib/feedback-marker.ts
- apps/course-builder-web/src/trpc/api/root.ts
- apps/course-builder-web/src/trpc/api/routers/articles.ts
- apps/course-builder-web/src/trpc/api/routers/writing.ts
- pnpm-lock.yaml
first step towards "markers" in the gutter or highlights etc
still working out the prompting and data validation for line numbers etc
[loom video](https://www.loom.com/share/70f13977b811449988e06c91d55d4ff9?sid=88a83f8c-fa4e-4054-9c23-361ca6179f05)
> feat: generate ai feedback for body text in article (or others)

- apps/course-builder-web/package.json
- apps/course-builder-web/src/app/[article]/page.tsx
- apps/course-builder-web/src/app/tips/[slug]/edit/page.tsx
- apps/course-builder-web/src/app/tips/[slug]/opengraph-image.tsx
- apps/course-builder-web/src/app/tips/[slug]/page.tsx
- apps/course-builder-web/src/app/tips/_components/edit-tip-form.tsx
- apps/course-builder-web/src/app/tips/_components/tip-player.tsx
- cli/package.json
- cli/template/base/package.json
- docs/package.json
- package.json
- packages/config/eslint-config/package.json
- packages/config/eslint-plugin/package.json
- packages/ui/package.json
- pnpm-lock.yaml
this lets us cross the client barrier with the promise and use the `use` hook to stream the results in
less blocking overall!
> feat: only create a single promise and pass it down as a loader

- apps/course-builder-web/src/app/_components/assistant-workflow-selector.tsx
- apps/course-builder-web/src/app/_components/resource-assistant.tsx
- apps/course-builder-web/src/app/articles/_components/article-assistant.tsx
- apps/course-builder-web/src/app/tips/_components/tip-assistant.tsx
- apps/course-builder-web/src/inngest/events.ts
- apps/course-builder-web/src/inngest/functions/articles/chat.ts
- apps/course-builder-web/src/inngest/functions/tips/chat.ts
- apps/course-builder-web/src/inngest/helpers/resource-chat.ts
- apps/course-builder-web/src/trpc/api/routers/articles.ts
- apps/course-builder-web/src/trpc/api/routers/tips.ts
- packages/ui/package.json
- pnpm-lock.yaml
> feat: give me selectable prompts

- apps/course-builder-web/README.md
Just a few tweaks to get this to a runnable state
> docs: add some clarity for onboarding flow

- .changeset/healthy-chicken-smell.md
- apps/course-builder-web/src/app/tutorials/[module]/edit/page.tsx
- apps/course-builder-web/src/app/tutorials/new/page.tsx
- apps/course-builder-web/src/app/tutorials/page.tsx
- apps/course-builder-web/src/components/lesson-list/data/tree.ts
- apps/course-builder-web/src/components/lesson-list/tree.tsx
- apps/course-builder-web/src/components/module-edit.tsx
- apps/course-builder-web/src/components/resources-crud/create-resource-card.tsx
- apps/course-builder-web/src/components/resources-crud/create-resource-form.tsx
- apps/course-builder-web/src/db/schema.ts
- apps/course-builder-web/src/lib/tutorials-query.ts
- packages/core/src/adapters.ts
> feat: ability to construct a tutorial

- apps/course-builder-web/src/app/(content)/tips/_components/edit-tip-form-mobile.tsx
- apps/pro-aws/src/app/(content)/tips/_components/edit-tip-form-mobile.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/edit-lesson-form-metadata.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/edit-lesson-form.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/lesson-player.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/new-lesson-video-form.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/page.tsx
- apps/pro-aws/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/pro-aws/src/components/resources-crud/create-resource-page.tsx
- apps/pro-aws/src/lib/articles-query.ts
- apps/pro-aws/src/lib/lessons-query.ts
- apps/pro-aws/src/lib/tips-query.ts
- apps/pro-aws/src/lib/tips.ts
- apps/pro-aws/src/lib/tutorial.ts
- apps/pro-aws/src/lib/tutorials-query.ts
- apps/pro-aws/src/lib/video-resource-query.ts
- apps/pro-aws/src/trpc/api/root.ts
- apps/pro-aws/src/trpc/api/routers/videoResource.ts
- packages/ui/codemirror/editor.tsx
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
- packages/ui/resources-crud/edit-resources-form-mobile.tsx
- packages/ui/resources-crud/panels/edit-resources-body-panel.tsx
https://www.loom.com/share/5d1a3af772904b788e3ecc5c3959d4a7?sid=eb1288b5-4c87-4d6c-a771-1ba4945317a8
> feat: initial shape of tutorial for Pro AWS

- .github/workflows/apps.yaml
- .github/workflows/ci.yaml
- .github/workflows/cli-prerelease.yml
- .github/workflows/release-canary.yaml
- .github/workflows/release.yaml
> chore: update various actions

- .changeset/yellow-adults-talk.md
- apps/course-builder-web/src/inngest/functions/cloudinary/image-resource-created.ts
- apps/course-builder-web/src/inngest/functions/ocr/ocr-code-extractor.ts
- apps/course-builder-web/src/inngest/inngest.server.ts
- apps/pro-aws/src/inngest/functions/cloudinary/image-resource-created.ts
- apps/pro-aws/src/inngest/functions/ocr/ocr-code-extractor.ts
- apps/pro-aws/src/inngest/inngest.server.ts
- packages/core/src/inngest/co-gardener/resource-chat.ts
- packages/core/src/inngest/create-inngest-middleware.ts
- packages/core/src/inngest/video-processing/functions/generate-transcript-with-screnshots.ts
- packages/core/src/inngest/video-processing/functions/transcript-ready.ts
- packages/core/src/inngest/video-processing/functions/video-processing-error.ts
- packages/core/src/inngest/video-processing/functions/video-ready.ts
- packages/core/src/inngest/video-processing/functions/video-uploaded.ts
- packages/core/src/providers/index.ts
- packages/core/src/providers/partykit.ts
https://www.loom.com/share/937d20d923d346119cf805071bf9c9b9?sid=5bea5447-6f99-462f-82a1-e899dc1d71b0
> feat: partykit provider 🎈

- apps/pro-aws/src/app/(content)/tutorials/[module]/edit/_form.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/edit/actions.ts
- apps/pro-aws/src/app/(content)/tutorials/[module]/edit/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/page.tsx
- apps/pro-aws/src/app/(content)/tutorials/_components/edit-tutorial-form.tsx
- apps/pro-aws/src/components/lesson-list/pieces/tree/constants.ts
- apps/pro-aws/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/pro-aws/src/components/lesson-list/tree.tsx
- apps/pro-aws/src/components/tutorial-resources-edit.tsx
- apps/pro-aws/src/lib/tutorials-query.ts
- apps/pro-aws/src/styles/globals.css
- packages/ui/chat-assistant/resource-chat-assistant.tsx
- packages/ui/resources-crud/create-resource-form.tsx
> style(proaws): tutorial edit form

- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/edit-lesson-form-metadata.tsx
- apps/pro-aws/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/edit-lesson-form.tsx
- apps/pro-aws/src/lib/lessons.ts
- apps/pro-aws/src/styles/globals.css
> feat(proaws): ability to edit lesson description

- apps/pro-aws/src/ability.ts
- apps/pro-aws/src/trpc/api/routers/ability.ts
> feat: enhanced abilities for viewing free content

- .changeset/polite-readers-happen.md
- apps/pro-aws/src/inngest/events/lesson-completed.ts
- apps/pro-aws/src/inngest/inngest.server.ts
- apps/pro-aws/src/trpc/api/root.ts
- apps/pro-aws/src/trpc/api/routers/progress.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
> feat: trpc progress router for ProAWS

- apps/pro-aws/src/ability.ts
- apps/pro-aws/src/trpc/api/routers/ability.ts
```tsx
// example
const { data: abilityRules } = api.ability.getCurrentAbilityRules.useQuery({
lessonId: params.lesson,
moduleId: params.module,
})
const ability = createAppAbility(abilityRules || [])
const canView = ability.can('read', 'Content')
```
> fix(proaws): tutorial related user abilities

- .changeset/silent-cats-live.md
- apps/course-builder-web/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/course-builder-web/src/components/lesson-list/pieces/tree/tree-context.tsx
- apps/course-builder-web/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/course-builder-web/src/components/lesson-list/tree.tsx
- apps/course-builder-web/src/lib/products-query.ts
- apps/course-builder-web/src/path-to-purchase/welcome-page.tsx
- apps/course-builder-web/src/pricing/pricing.tsx
- apps/course-builder-web/src/trpc/api/root.ts
- apps/course-builder-web/src/trpc/api/routers/contentResources.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/commerce/product.ts
- packages/adapter-drizzle/test/fixtures.ts
- packages/core/src/schemas/content-resource-schema.ts
- packages/core/src/schemas/product-schema.ts
- packages/ui/primitives/command.tsx
- packages/utils/adapter.ts
- packages/utils/format-prices-for-product.test.ts
> feat: ability to add resources to products

- apps/course-builder-web/src/app/(commerce)/invoices/page.tsx
- apps/course-builder-web/src/app/(commerce)/thanks/purchase/page.tsx
- apps/course-builder-web/src/app/(content)/events/[slug]/_components/event-page-props.ts
- apps/course-builder-web/src/app/(user)/login/actions.ts
- apps/course-builder-web/src/app/(user)/team/page.tsx
- apps/course-builder-web/src/app/(user)/team/page_client.tsx
- apps/course-builder-web/src/coursebuilder/stripe-payment-adapter.ts
- apps/course-builder-web/src/pricing/buy-more-seats.tsx
- apps/course-builder-web/src/pricing/pricing.tsx
- apps/course-builder-web/src/purchase-transfer/purchase-transfer-actions.tsx
- apps/course-builder-web/src/purchase-transfer/purchase-transfer-status.tsx
- apps/course-builder-web/src/server/auth.ts
- apps/course-builder-web/src/styles/globals.css
- apps/course-builder-web/src/styles/team.css
- apps/course-builder-web/src/team/claimed-team-seats.tsx
- apps/course-builder-web/src/team/copy-invite-link.tsx
- apps/course-builder-web/src/team/index.tsx
- apps/course-builder-web/src/uploadthing/core.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/commerce/coupon.ts
- packages/core/src/adapters.ts
- packages/core/src/lib/utils/logger.ts
- packages/core/src/providers/stripe.ts
- packages/core/src/schemas/user-schema.ts
> feat: post purchase team management

- apps/pro-aws/src/app/(commerce)/thanks/purchase/page.tsx
- apps/pro-aws/src/coursebuilder/slack-provider.ts
- apps/pro-aws/src/env.mjs
- apps/pro-aws/src/inngest/inngest.server.ts
- packages/commerce-next/src/post-purchase/purchase-transfer.tsx
- packages/core/package.json
- packages/core/src/inngest/commerce/event-new-purchase-created.ts
- packages/core/src/inngest/commerce/send-creator-slack-notification.ts
- packages/core/src/inngest/commerce/send-post-purchase-email.ts
- packages/core/src/inngest/create-inngest-middleware.ts
- packages/core/src/inngest/index.ts
- packages/core/src/inngest/stripe/event-checkout-session-completed.ts
- packages/core/src/lib/send-verification-request.ts
- packages/core/src/providers/index.ts
- packages/core/src/providers/slack.ts
- pnpm-lock.yaml
> feat: add a slack provider

- .changeset/large-rabbits-hug.md
- apps/course-builder-web/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/course-builder-web/src/app/(content)/articles/_components/edit-article-form.tsx
- apps/course-builder-web/src/app/(content)/events/[slug]/edit/_components/edit-event-form.tsx
- apps/course-builder-web/src/components/lesson-list/pieces/tree/constants.ts
- apps/course-builder-web/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/epic-web/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/epic-web/src/app/(content)/articles/_components/edit-article-form.tsx
- apps/epic-web/src/app/(content)/events/[slug]/edit/_components/edit-event-form.tsx
- apps/pro-aws/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/pro-aws/src/app/(content)/events/[slug]/edit/_components/edit-event-form.tsx
- apps/pro-aws/src/app/(content)/tutorials/_components/edit-tutorial-form.tsx
- apps/pro-aws/src/components/lesson-list/pieces/tree/constants.ts
- apps/pro-aws/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/pro-nextjs/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/pro-nextjs/src/app/(content)/articles/_components/edit-article-form.tsx
- apps/pro-nextjs/src/app/(content)/events/[slug]/edit/_components/edit-event-form.tsx
- apps/pro-nextjs/src/app/(content)/tutorials/_components/edit-tutorial-form.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/edit-workshop-form.tsx
- apps/pro-nextjs/src/app/api/og/route.tsx
- apps/pro-nextjs/src/components/lesson-list/pieces/tree/constants.ts
- apps/pro-nextjs/src/components/lesson-list/pieces/tree/tree-item.tsx
- apps/pro-nextjs/src/components/workshop-resources-edit.tsx
- apps/value-based-design/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/value-based-design/src/app/(content)/articles/_components/edit-article-form.tsx
- apps/value-based-design/src/app/(content)/events/[slug]/edit/_components/edit-event-form.tsx
- packages/ui/resources-crud/edit-resources-tool-panel.tsx
- packages/ui/resources-crud/edit-resources-toolbar.tsx
https://github.com/badass-courses/course-builder/assets/25487857/7523735f-b2bd-483e-a634-9238efcec0df
> style: resource list

- apps/pro-nextjs/src/app/(content)/workshops/[module]/edit/actions.ts
- apps/pro-nextjs/src/app/(content)/workshops/_components/edit-workshop-form.tsx
- apps/pro-nextjs/src/components/lesson-list/tree.tsx
- apps/pro-nextjs/src/lib/workshops-query.ts
- packages/ui/resources-crud/edit-resources-action-bar.tsx
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
> fix(pnjs): workshop saving

- .changeset/quiet-jokes-fail.md
- apps/pro-nextjs/src/app/(commerce)/products/[slug]/edit/_components/edit-product-form.tsx
- apps/pro-nextjs/src/app/(commerce)/products/[slug]/edit/page.tsx
- apps/pro-nextjs/src/app/(commerce)/products/[slug]/page.tsx
- apps/pro-nextjs/src/app/api/og/route.tsx
- apps/pro-nextjs/src/lib/products-query.ts
- apps/pro-nextjs/src/trpc/api/routers/contentResources.ts
- packages/commerce-next/src/pricing/pricing.tsx
- packages/core/src/schemas/product-schema.ts
> feat(pnjs): enable commerce and add first course product

- apps/value-based-design/src/app/(content)/workshops/[module]/[lesson]/edit/_components/edit-lesson-form.tsx
> feat(vbd): media browser in lesson edit

- apps/pro-nextjs/src/ability/index.ts
- apps/pro-nextjs/src/ability/purchase-validators.test.ts
- apps/pro-nextjs/src/ability/purchase-validators.ts
- apps/pro-nextjs/src/app/(content)/workshops/_components/tutorial-lesson-list.tsx
- apps/pro-nextjs/src/lib/modules-query.ts
- apps/pro-nextjs/src/utils/get-current-ability-rules.ts
> feat(pnjs): module purchase validation abilities

- .changeset/lazy-geese-return.md
- apps/pro-nextjs/src/app/(content)/_components/video-player-overlay.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/exercise/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/shared-page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/solution/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/pricing-widget.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/video-overlay-pricing-widget.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-pricing-server.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-pricing.tsx
- packages/commerce-next/src/pricing/props-for-commerce.ts
> feat(pnjs): video overlay pricing widget

- .changeset/mean-clocks-sniff.md
- apps/course-builder-web/src/app/(content)/tutorials/[module]/[lesson]/edit/_components/edit-lesson-form-metadata.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/edit/_components/edit-lesson-form-metadata.tsx
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/core/src/adapters.ts
- packages/core/src/inngest/video-processing/functions/video-uploaded.ts
> feat: ability to remove and reupload a video

- apps/value-based-design/src/app/(user)/profile/_components/edit-profile-form.tsx
- apps/value-based-design/src/app/(user)/profile/page.tsx
- apps/value-based-design/src/trpc/api/routers/users.ts
Brings over profile page from skillstack that allows users to update their names
> feat(vbd): add basic profile

- apps/pro-nextjs/src/app/sitemap.ts
> feat(pnjs): dynamic sitemap

- .changeset/calm-plums-compete.md
- .changeset/strange-clouds-exist.md
- apps/pro-nextjs/src/app/_components/home-pricing-widget.tsx
- apps/pro-nextjs/src/styles/globals.css
- apps/pro-nextjs/src/styles/team.css
- packages/commerce-next/src/post-purchase/buy-more-seats.tsx
- packages/commerce-next/src/pricing/price-display.tsx
- packages/commerce-next/src/pricing/pricing-context.tsx
- packages/commerce-next/src/pricing/pricing-state-machine.ts
- packages/commerce-next/src/pricing/pricing.tsx
- packages/core/src/lib/actions/index.ts
- packages/core/src/lib/index.ts
- packages/core/src/lib/utils/actions.ts
- packages/core/src/types.ts
> feat(pnjs): add purchased state to pricing widget & ability to buy more seats

- apps/pro-nextjs/src/app/_components/home-pricing-widget.tsx
- packages/commerce-next/src/pricing/pricing.tsx
> feat(pnjs): product sale countdown for pricing widget

- .changeset/many-ants-tap.md
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/commerce/coupon.ts
- packages/commerce-next/src/coupons/redeem-full-price-coupon.ts
- packages/core/src/lib/pricing/stripe-checkout.ts
- packages/core/src/schemas/coupon-schema.ts
> fix(cb): properly identify bulk purchases

- .changeset/beige-rice-jog.md
- apps/course-builder-web/src/app/(user)/team/page.tsx
- apps/epic-web/src/app/(user)/team/page.tsx
- apps/pro-aws/src/app/(user)/team/page.tsx
- apps/pro-nextjs/src/app/(user)/team/page.tsx
- apps/value-based-design/src/app/(user)/team/page.tsx
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/commerce/coupon.ts
- packages/commerce-next/src/coupons/coupon-context.tsx
- packages/commerce-next/src/team/claimed-team-seats.tsx
- packages/core/src/adapters.ts
- packages/core/src/schemas/coupon-schema.ts
> chore(cb): remove bulkPurchaseId from coupon and change redeemed bulk purchase relationship

- .changeset/giant-dolls-drop.md
- apps/pro-nextjs/src/app/(user)/team/page.tsx
- apps/pro-nextjs/src/app/(user)/team/page_client.tsx
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/commerce-next/src/team/claimed-team-seats.tsx
> fix(pnjs): claimed team seats renderer

- apps/pro-nextjs/src/app/(content)/tutorials/[module]/[lesson]/(view)/page.tsx
- apps/pro-nextjs/src/app/(content)/tutorials/_components/tutorial-lesson-progress-toggle.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/layout.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/[lesson]/(view)/shared-page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/layout.tsx
- apps/pro-nextjs/src/app/(content)/workshops/[module]/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/module-lesson-progress-toggle.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/next-lesson-button.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/preview-workshop-button.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-progress-provider.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-resource-list.tsx
- apps/pro-nextjs/src/lib/progress.ts
- apps/pro-nextjs/src/lib/workshops-query.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
https://www.loom.com/share/f36fad0388054094bc309c325e491aa7?sid=9a4b42bd-ff34-43e5-a390-b1fbcde84cf1
> chore(pnjs): module progress and navigation data loading

- apps/value-based-design/src/app/_components/landing-copy.mdx
> chore: Update landing-copy.mdx from nickd

- apps/js-visualized/src/app/_components/landing-copy.mdx
- apps/js-visualized/src/app/layout.tsx
- apps/js-visualized/src/components/curved-line-intersection.tsx
- apps/js-visualized/src/components/landing/hero.tsx
- apps/js-visualized/src/components/landing/introduce-author.tsx
- apps/js-visualized/src/components/landing/introducing.tsx
- apps/js-visualized/src/components/landing/more-clear-as-visualization.tsx
- apps/js-visualized/src/components/landing/question-and-answer.tsx
- apps/js-visualized/src/components/landing/question-or-answer-card.tsx
- apps/js-visualized/src/components/landing/snippet-with-glow.tsx
- apps/js-visualized/src/components/landing/what-you-will-learn.tsx
- apps/js-visualized/src/components/navigation.tsx
- apps/js-visualized/src/components/navigation/links.tsx
- apps/js-visualized/src/components/primary-newsletter-cta.tsx
- apps/js-visualized/src/hooks/use-smooth-scroll.ts
- apps/js-visualized/src/styles/globals.css
- apps/js-visualized/src/styles/subscribe-form.css
- apps/js-visualized/tailwind.config.ts
This implements:
1. styles for all resolutions (xs, sm, md, lg, xl, 2xl)
2. smooth scrolling animation to the subscribe form
3. hover animations for the buttons
<details>
<summary>XS (up to 639)</summary>
</details>
<details>
<summary>SM (640-766)</summary>
</details>
<details>
<summary>MD (768-1023)</summary>
</details>
<details>
<summary>LG (1024-1279)</summary>
</details>
<details>
<summary>XL (1280-1439)</summary>
</details>
<details>
<summary>2XL (1440 an more)</summary>
</details>
> feat(jsv): landing page: iteration #5

- apps/pro-nextjs/src/app/(content)/_components/video-player-overlay.tsx
- apps/pro-nextjs/src/app/(content)/tutorials/[module]/[lesson]/(view)/page.tsx
- apps/pro-nextjs/src/app/(content)/tutorials/[module]/layout.tsx
- apps/pro-nextjs/src/app/(content)/tutorials/_components/tutorial-lesson-list.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-navigation-provider.tsx
- apps/pro-nextjs/src/lib/workshops-query.ts
> fix: navigation data loading for tutorials

- apps/pro-nextjs/src/app/(content)/_components/authed-video-player.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-resource-list.tsx
> fix(pnjs): revalidate after completing on autoplay

- apps/pro-nextjs/src/app/(content)/workshops/[module]/page.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-navigation-provider.tsx
- apps/pro-nextjs/src/app/(content)/workshops/_components/workshop-resource-list.tsx
> feat(pnjs): collapsible workshop navigation sidebar

- apps/value-based-design/src/app/(content)/workshops/[module]/[lesson]/(view)/shared-page.tsx
- apps/value-based-design/src/app/(content)/workshops/_components/lesson-description.tsx
> feat(vbd): hide lesson body contents to non-purchasers

- apps/value-based-design/src/components/app/use-nav-links.tsx
> feat(vbd): add pro workshops nav link

- apps/value-based-design/src/inngest/inngest.server.ts
Adds slack provider for purchase notifications
> feat(vbd): Set up a dd channel for valuebased.design

- apps/egghead/src/app/(content)/[post]/page.tsx
- apps/egghead/src/app/(content)/posts/[slug]/edit/page.tsx
- apps/egghead/src/app/(content)/posts/_components/edit-post-form-mobile.tsx
- apps/egghead/src/app/(content)/posts/_components/edit-post-form.tsx
- apps/egghead/src/app/(content)/posts/page.tsx
This restricts editing and deleting for contributors to only resources that match their user Id
> feat(egh): restrict delete and edit ability to createdById

- apps/egghead/src/app/(content)/posts/page.tsx
- apps/egghead/src/lib/posts-query.ts
> feat(egh): only load contributer posts for contributers

- apps/epic-react/package.json
- apps/epic-react/src/db/generated/meta/_journal.json
- apps/epic-web/package.json
- apps/epic-web/tailwind.config.ts
- pnpm-lock.yaml
> fix(ewd): build

- packages/ui/chat-assistant/resource-chat-assistant.tsx
- packages/ui/chat-assistant/resource-chat-response.tsx
- packages/ui/primitives/scroll-area.tsx
- packages/ui/resources-crud/edit-resources-tool-panel-contents.tsx
- packages/ui/resources-crud/panels/edit-resources-metadata-panel.tsx
- set user messages in react context so they can be displayed instantly instead of waiting for socket response
- add loading state when waiting for assistant response
- add `copy to clipboard` button to message `pre` blocks
https://github.com/user-attachments/assets/facb6a66-4605-49f2-908f-791cba4edc7f
> feat(ui): chat assistant with optimistic updates and loading state

- apps/astro-party/drizzle.config.ts
- apps/astro-party/src/db/schema.ts
- apps/course-builder-video-blog/src/db/schema.ts
- apps/course-builder-web/src/db/schema.ts
- apps/egghead/src/app/(content)/posts/[slug]/edit/page.tsx
- apps/egghead/src/app/page.tsx
- apps/egghead/src/db/schema.ts
- apps/egghead/src/lib/posts-query.ts
- apps/egghead/src/lib/posts.ts
- apps/epic-react/src/db/schema.ts
- apps/epic-web/src/db/schema.ts
- apps/js-visualized/src/db/schema.ts
- apps/pro-aws/src/db/schema.ts
- apps/pro-nextjs/src/db/schema.ts
- apps/total-node/src/db/schema.ts
- apps/value-based-design/src/db/schema.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/content/content-resource-version.ts
- packages/adapter-drizzle/src/lib/mysql/schemas/content/content-resource.ts
- packages/core/src/schemas/content-resource-schema.ts
- packages/utils/adapter.ts
simple data model for versioning content resources implemented for Posts in egghead builder project
> feat: course builder content resource versioning

- apps/egghead/src/app/(content)/[post]/page.tsx
- apps/egghead/src/app/(content)/posts/[slug]/edit/actions.ts
- apps/egghead/src/app/(content)/posts/_components/edit-post-form.tsx
- apps/egghead/src/app/_components/share-post-modal.tsx
- apps/egghead/src/app/_components/share.tsx
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
This provides a CTA when instructors publish a post. This is done by pushing a query param `published=true` using the `onPublished` callback in  `EditResourcesFormDesktop`
> feat(egh): prompt to share on publish

- apps/ai-hero/package.json
- apps/ai-hero/scripts/index-content.ts
- apps/ai-hero/src/app/(search)/q/_components/infinite-hits.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/clear-refinements.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/current-refinements.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/hit.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/hits-per-page-select.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/refinement-list.tsx
- apps/ai-hero/src/app/(search)/q/_components/instantsearch/searchbox.tsx
- apps/ai-hero/src/app/(search)/q/_components/search.tsx
- apps/ai-hero/src/app/(search)/q/page.tsx
- apps/ai-hero/src/app/_components/providers.tsx
- apps/ai-hero/src/env.mjs
- apps/ai-hero/src/lib/posts-query.ts
- apps/ai-hero/src/lib/posts.ts
- apps/ai-hero/src/lib/typesense-query.ts
- apps/ai-hero/src/lib/typesense.ts
- apps/ai-hero/src/utils/typesense-instantsearch-adapter.ts
- pnpm-lock.yaml
this will come in handy at some point, both for content production (adding resources to a collection) and consumption (a feed).
> feat(ai): implement basic search and post indexing with typesense

- apps/ai-hero/party/index.ts
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form.tsx
- apps/ai-hero/src/inngest/functions/create-user-organization.ts
- apps/ai-hero/src/inngest/inngest.config.ts
- apps/ai-hero/src/inngest/inngest.server.ts
- apps/astro-party/party/index.ts
- apps/egghead/party/index.ts
- apps/epic-react/party/index.ts
- apps/go-local-first/party/index.ts
- apps/pro-aws/party/index.ts
- apps/pro-nextjs/party/index.ts
- apps/value-based-design/party/index.ts
- packages/ui/resources-crud/edit-resources-action-bar.tsx
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
- packages/ui/resources-crud/panels/edit-resources-body-panel.tsx
this uses the ydoc binary file for updates instead of raw text which should generally fix the previous issues with double+ text
> feat: partykit editor

- packages/ui/hooks/use-auto-save.ts
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
> feat(ui): improved auto-save that only triggers after timeout of no typing and cancels pending saves when new typing occurs

- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form.tsx
- apps/ai-hero/src/lib/posts-query.ts
- packages/ui/resources-crud/edit-resources-form-desktop.tsx
> feat(ui): ability to opt-out from resource revalidation when update occurs

- .changeset/brown-trees-shout.md
- packages/core/src/lib/send-verification-request.ts
> feat(core): create subscriber with name

- .changeset/config.json
- .changeset/lovely-cooks-tap.md
- apps/ai-hero/package.json
- apps/astro-party/package.json
- apps/course-builder-web/package.json
- apps/egghead/package.json
- apps/epic-react/package.json
- apps/go-local-first/package.json
- cli/package.json
- packages/commerce-next/package.json
- packages/next/package.json
- pnpm-lock.yaml
> chore: bump next canary

- apps/ai-hero/src/app/(content)/[post]/_components/recommendations.tsx
- apps/ai-hero/src/app/(content)/_components/post-next-up-from-list-pagination.tsx
- apps/ai-hero/src/app/(content)/posts/_components/post-player.tsx
- apps/ai-hero/src/lib/typesense-query.ts
- apps/ai-hero/src/trpc/api/root.ts
- apps/ai-hero/src/trpc/api/routers/typesense.ts
> feat(aih): vector search driven recs

- .changeset/green-buckets-return.md
- apps/ai-hero/src/app/(content)/posts/[slug]/edit/page.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form-metadata.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form-mobile.tsx
- apps/ai-hero/src/app/(content)/posts/_components/edit-post-form.tsx
- packages/core/src/inngest/co-gardener/resource-chat.ts
> feat(aih): add description generation for posts

- apps/ai-hero/src/app/(content)/posts/page.tsx
- apps/ai-hero/src/lib/pages-query.ts
> feat(aih): streamline featured posts curation

- .changeset/hot-cheetahs-lie.md
- apps/ai-hero/src/app/(content)/cohorts/[slug]/edit/_components/edit-cohort-form.tsx
- apps/ai-hero/src/components/list-editor/lesson-list/data/tree.ts
- apps/ai-hero/src/components/list-editor/lesson-list/pieces/tree/tree-item.tsx
- apps/ai-hero/src/components/list-editor/lesson-list/tree.tsx
- apps/ai-hero/src/components/list-editor/list-resources-edit.tsx
- apps/ai-hero/src/components/list-editor/resources-infinite-hits.tsx
- apps/ai-hero/src/inngest/functions/post-cohort-purchase-workflow.ts
- apps/ai-hero/src/lib/lists-query.ts
- apps/ai-hero/src/lib/resources-query.ts
- apps/ai-hero/src/lib/tutorials-query.ts
- packages/adapter-drizzle/src/lib/mysql/index.ts
- packages/core/src/inngest/stripe/event-checkout-session-completed.ts
we need to be able to add content to specific cohorts and designate the content for specific tiers standard premium VIP
https://www.loom.com/share/9d64401e9ca34bd296085ac7d92c409f
> feat: cohort content resources with tier metadata

- apps/ai-hero/src/app/(content)/posts/_components/create-post.tsx
- apps/ai-hero/src/components/list-editor/draggable-item-renderer.tsx
- apps/ai-hero/src/components/list-editor/lesson-list/pieces/tree/tree-context.tsx
- apps/ai-hero/src/components/list-editor/lesson-list/pieces/tree/tree-item.tsx
- apps/ai-hero/src/components/list-editor/lesson-list/tree.tsx
- apps/ai-hero/src/components/list-editor/list-resources-edit.tsx
- apps/ai-hero/src/components/list-editor/resource-list.tsx
- apps/ai-hero/src/components/list-editor/search-config.tsx
- apps/ai-hero/src/components/resources-crud/new-resource-with-video-form.tsx
I wanted to get the instantsearch hook out of the tree component and do some work on general composability with the list
> chore: tree component composability

- apps/ai-hero/package.json
- apps/ai-hero/src/utils/compile-mdx.tsx
- packages/mdx-mermaid/package.json
- packages/mdx-mermaid/src/client.tsx
- packages/mdx-mermaid/src/index.ts
- packages/mdx-mermaid/src/remarkPlugin.ts
- packages/mdx-mermaid/tsconfig.json
- packages/mdx-mermaid/tsup.config.ts
- pnpm-lock.yaml
Introduced a new package @coursebuilder/mdx-mermaid to enable Mermaid diagram rendering in MDX content. The implementation includes:
- A remark plugin to transform Mermaid code blocks into React components
- A client-side Mermaid rendering component with theme and configuration support
- Integration with the AI Hero app's MDX compilation process
> feat: add Mermaid diagram support for MDX content

- apps/epicdev-ai/src/emails/welcome-email.tsx
- apps/epicdev-ai/src/inngest/functions/post-purchase-automation/send-welcome-email.ts
> feat(eai): enhance welcome email for live events
